language: node_js
node_js:
- '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: vYgGrshIlaeH5FSgq1CBXeJts6QpA2ZA3cFNW0b8t0ZHT3tosPHvyPk4rQvjsOMCki1ZnbY4B9FIf6tKL6gvnjk5YlszZ9l4kwXZolRiXmMzG/PfaW2fsU3Oa5TSBOPZqtHtHc7GOGp/d7QSIY4UtGrVw7xI/kdffqoQ5XhcrJzJRNaIi0DADqQ0HCwS9sSJtxZPh8IGabjnuy8qmxku9H6CyR9YFmGAUSa64xw7ZgY0BSKQZRsOE3giY0qb4hDapuSbP8KG9/xQObehiX/ilNnapO5YX4qYLu4y59Da27GK782MRoWfFC8EPk+ICsQea+BdELEJjZXMrGSugp6CrjhNyBJmxueSSDL0cL5QnHZSbSx27dZzvUtL26+q1KXHdsgHa0lNVxzE1sXfpFfpPZxNRo11Opyyqnv3gKAP8iyUzwgK/tTRhMLU14UUiBPguhIyQA0H/mWJo0AFGdLt/dhDP/sgx6eUuKKtGk3XucBLtM0eftMKr9X00zkVuLOGo3VPLZuaUsgPPxEQsAj/gFBrr9h3lH8AFgwkuaY4y7frDjbJqbtjH3gQTGbH+zri5uCJC7zd2+oZNZKZQHH7RaZpFkrKpakIbgMgV3JR1ee7gxQ7JDxtjiH0SOHZ2Dm2Z2fVklndWcm0M7S7sn4OlEBRcIDBjIYx5HUb1dth5Ng=
  on:
    repo: kuzzleio/boost-geospatial-index
    branch: master
